version: '3'
services:
    py-server:
        image: alisson/djprova
        build: .
        ports:
         - "9000:9000"
        container_name: djprova
        volumes:
         - ./ProvaCamacho:/src
        working_dir: /src
        command: python3 /src/manage.py runserver 0.0.0.0:9000
